ALTER TABLE public.pengaduans
ADD COLUMN IF NOT EXISTS token TEXT,
ADD COLUMN IF NOT EXISTS nama_pelapor TEXT,
ADD COLUMN IF NOT EXISTS telp_pelapor TEXT,
ADD COLUMN IF NOT EXISTS nama_terlapor TEXT,
ADD COLUMN IF NOT EXISTS lokasi_aduan TEXT,
ADD COLUMN IF NOT EXISTS deskripsi TEXT,
ADD COLUMN IF NOT EXISTS status_tahapan TEXT DEFAULT 'Menunggu Isian';
